### PR TITLE
RHDM-349: Added project that contains only drools and optaplanner examples

### PR DESCRIPTION
**Pull request by adrielparedes**
@porcelli could you review?

https://issues.jboss.org/browse/RHDM-349

Related to:
https://github.com/kiegroup/optaplanner-wb/pull/250
https://github.com/kiegroup/drools-wb/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/692
https://github.com/kiegroup/kie-drools-wb-playground/pull/1
https://github.com/kiegroup/kie-wb-distributions/pull/685

### CODE REVIEW

**Comment by adrielparedes** [comment]
@mbiarnes well jenkins doen't work, may be tomorrow we could check this :)

**Comment by mbiarnes** [comment]
check it out pls and tell me if it is working now

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Hi Adriel,

Some questions:
- should kie-drools-wb-playground should be part of the build (dailyBuilds
and releases)
- if so it should be added to
../droolsjbpm-build-bootstrap/script/repository-list.txt
- is this dependent of another repo to build first
- are there downstream reps dependent of this one

​Michael​



On Tue, Feb 6, 2018 at 11:10 AM, Michael Biarnes Kiefer <mbiarnes@redhat.com

**Comment by adrielparedes** [comment]
@mbiarnes don't worry about this project I think it is going to be deleted. I'm finishing a better solution to have the old repo with all we need. So when I finish I will delete it. If you want you could delete jenkins job. Thanks a lot for the help!

**Comment by mbiarnes** [comment]
OK - I will remove the Jenkins Jobs then -(they are anyway red :)

**Comment by adrielparedes** [comment]
Closing this issue. This is not going to happen

**Pull request closed without merging**
